
export default function TermsOfService() {
  return (
    <main className="container mx-auto px-4 pt-32 pb-16 min-h-[60vh]">
      <div className="max-w-4xl mx-auto">
        <h1 className="text-4xl font-bold mb-2 text-slate-900">Terms of Service</h1>
        <p className="text-slate-500 mb-8">Last Updated: January 30, 2026</p>

        <div className="prose prose-slate max-w-none text-slate-700">

          {/* 1. Acceptance of Terms */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">1. Acceptance of Terms</h2>
            <p className="mb-4">
              These Terms of Service (&quot;Terms&quot;) constitute a legally binding agreement between you (&quot;User,&quot; &quot;you,&quot; or &quot;your&quot;) and Polyhistor LLC (&quot;Company,&quot; &quot;we,&quot; &quot;us,&quot; or &quot;our&quot;). By accessing, downloading, installing, or using the Polyhistor mobile application (the &quot;App&quot;) and related services (collectively, the &quot;Service&quot;), you acknowledge that you have read, understood, and agree to be bound by these Terms.
            </p>
          </section>

          {/* 2. Eligibility */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">2. Eligibility</h2>
            <p className="mb-4">
              The Service is strictly intended for users who are 13 years of age or older. By using the Service, you represent and warrant that you are at least 13 years old and have the full right, power, and authority to enter into these Terms.
            </p>
          </section>

          {/* 3. Accounts and Security */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">3. Accounts and Security</h2>
            <p className="mb-4">To access certain features, you must register for an account.</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Security:</strong> You are responsible for safeguarding your account credentials. You agree to notify us immediately at <a href="mailto:legal@thepolyhistor.com" className="text-brand-blue hover:underline">legal@thepolyhistor.com</a> of any unauthorized use.</li>
              <li><strong>Liability:</strong> You are solely responsible for all activities that occur under your account.</li>
            </ul>
          </section>

          {/* 4. User Conduct & Moderation (Zero Tolerance) */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">4. User Conduct & Moderation (Zero Tolerance)</h2>
            <p className="mb-4">We enforce a Zero Tolerance Policy for objectionable content to ensure a safe community. You agree NOT to:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Harass, abuse, defame, threaten, or bully other users.</li>
              <li>Post hate speech, violence, sexually explicit content, or illegal material.</li>
              <li>Spam or use the Service for unauthorized commercial advertising.</li>
            </ul>
            <p className="mb-4"><strong>Enforcement:</strong> We reserve the right to monitor content and may:</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li>Remove any content that violates these Terms.</li>
              <li>Ban or suspend your account immediately and without notice if you are found violating these standards.</li>
            </ul>
          </section>

          {/* 5. AI Services & Disclaimers */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">5. AI Services & Disclaimers</h2>
            <p className="mb-4">The Service includes AI-powered features (e.g., itinerary generation) using technologies like Google Gemini.</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Accuracy:</strong> AI suggestions may contain errors or &quot;hallucinations.&quot; You acknowledge that opening hours, prices, and locations generated by AI may be incorrect.</li>
              <li><strong>No Reliance:</strong> You agree to verify all AI-generated travel details independently. Polyhistor LLC is not liable for missed flights, closed attractions, or other inconveniences resulting from your reliance on AI data.</li>
            </ul>
          </section>

          {/* 6. Agency & Group Travel */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">6. Agency & Group Travel</h2>
            <p className="mb-4">If you use the App to join a trip organized by a third-party Travel Agency (&quot;Agency&quot;):</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Independent Entity:</strong> The Agency is independent of Polyhistor LLC. We provide the platform but do not control the Agency&apos;s services.</li>
              <li><strong>Data Visibility:</strong> You acknowledge that the Agency may have access to your trip progress and location during active Agency trips.</li>
            </ul>
          </section>

          {/* 7. Location Services */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">7. Location Services</h2>
            <p className="mb-4">The Service utilizes location-based features for navigation and social tracking.</p>
            <ul className="list-disc pl-6 space-y-2 mb-4">
              <li><strong>Voluntary Sharing:</strong> You acknowledge that sharing your real-time location with friends or Agencies is voluntary.</li>
              <li><strong>Safety:</strong> You must always exercise caution and obey traffic laws. We are not liable for accidents or damages resulting from your use of the navigation features while driving or walking.</li>
            </ul>
          </section>

          {/* 8. User Content License */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">8. User Content License</h2>
            <p className="mb-4">
              You retain ownership of your photos, itineraries, and messages (&quot;User Content&quot;). By posting User Content, you grant Polyhistor LLC a worldwide, royalty-free license to use, display, and distribute your content solely for the purpose of operating and improving the Service.
            </p>
          </section>

          {/* 9. Intellectual Property */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">9. Intellectual Property</h2>
            <p className="mb-4">
              The Service and its original content (excluding User Content), features, and functionality are the exclusive property of Polyhistor LLC and its licensors.
            </p>
          </section>

          {/* 10. DMCA Copyright Policy */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">10. DMCA Copyright Policy</h2>
            <p className="mb-4">
              If you believe your copyrighted work has been infringed on the Service, please submit a written notice to <a href="mailto:legal@thepolyhistor.com" className="text-brand-blue hover:underline">legal@thepolyhistor.com</a>. We will respond to valid notices and terminate accounts of repeat infringers.
            </p>
          </section>

          {/* 11. Disclaimer of Warranties */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">11. Disclaimer of Warranties</h2>
            <p className="uppercase text-sm leading-relaxed">
              THE SERVICE IS PROVIDED &quot;AS IS&quot; AND &quot;AS AVAILABLE.&quot; WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE SERVICE, INCLUDING ACCURACY OF MAP DATA, AI RESULTS, OR UPTIME.
            </p>
          </section>

          {/* 12. Limitation of Liability */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">12. Limitation of Liability</h2>
            <p className="uppercase text-sm leading-relaxed">
              TO THE FULLEST EXTENT PERMITTED BY LAW, THEPOLYHISTOR LLC SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING LOSS OF PROFITS, DATA, OR GOODWILL, ARISING FROM: (A) YOUR USE OF THE SERVICE; (B) CONDUCT OF ANY THIRD PARTY (INCLUDING OTHER USERS OR AGENCIES); OR (C) ERRORS IN AI OR NAVIGATION DATA.
            </p>
          </section>

          {/* 13. Governing Law */}
          <section className="mb-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">13. Governing Law</h2>
            <p className="mb-4">
              These Terms shall be governed by the laws of the State of Illinois, without regard to its conflict of law provisions.
            </p>
          </section>

          {/* 14. Contact Us */}
          <section className="mb-8 border-t border-slate-200 pt-8">
            <h2 className="text-2xl font-bold text-slate-900 mb-4">14. Contact Us</h2>
            <p>
              Polyhistor LLC <br /> Email: <a href="mailto:legal@thepolyhistor.com" className="text-brand-blue hover:underline">legal@thepolyhistor.com</a>
            </p>
          </section>

        </div>
      </div>
    </main>
  );
}
